#!/bin/bash
set -eu

if [ develop = "${1:-}" ]
then
    if [ ! -e up-tests.pid ]
    then
        echo "up-tests pidfile not found"
        exit 2
    fi
    pkill -g "$(< up-tests.pid)"
    rm develop.pid
fi

docker-compose down -v
