#!/bin/bash
set -eu

ipath=$(mktemp -d "${TMPDIR:-/tmp}"/dl-registry-tests-XXXX)
: "${DATALAD_REGISTRY_INSTANCE_PATH:=$ipath/instance}"
: "${DATALAD_REGISTRY_DB_INSTANCE_PATH:=$ipath/db}"
export DATALAD_REGISTRY_INSTANCE_PATH
export DATALAD_REGISTRY_DB_INSTANCE_PATH

./up

for i in $(seq 30)
do
    echo "Checking for Flask server connection (try $i)..."
    if ! nc -nvz 127.0.0.1 5000
    then
        sleep 5
    else
        exit 0
    fi
done

exit 1
