"""Add  the to the  model

Revision ID: a26ee17e3a75
Revises: 08c8e8731782
Create Date: 2023-04-16 19:36:25.075107

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a26ee17e3a75"
down_revision = "08c8e8731782"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cache_path", sa.String(length=34), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.drop_column("cache_path")

    # ### end Alembic commands ###
