"""Rename model URL to RepoUrl

Revision ID: a398e7225012
Revises: c6873af75bd6
Create Date: 2023-07-08 21:43:12.767961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a398e7225012"
down_revision = "c6873af75bd6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repo_url",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("ds_id", sa.Text(), nullable=True),
        sa.Column("annex_uuid", sa.Text(), nullable=True),
        sa.Column("annex_key_count", sa.Integer(), nullable=True),
        sa.Column("annexed_files_in_wt_count", sa.Integer(), nullable=True),
        sa.Column("annexed_files_in_wt_size", sa.BigInteger(), nullable=True),
        sa.Column("head", sa.Text(), nullable=True),
        sa.Column("head_describe", sa.Text(), nullable=True),
        sa.Column("head_dt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("branches", sa.Text(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("git_objects_kb", sa.BigInteger(), nullable=True),
        sa.Column("last_update_dt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_chk_dt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chk_req_dt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("n_failed_chks", sa.Integer(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("cache_path", sa.String(length=34), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.drop_table("url")
    with op.batch_alter_table("url_metadata", schema=None) as batch_op:
        batch_op.drop_constraint("url_metadata_url_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(None, "repo_url", ["url_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url_metadata", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "url_metadata_url_id_fkey", "url", ["url_id"], ["id"]
        )

    op.create_table(
        "url",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("ds_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("annex_uuid", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("annex_key_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "annexed_files_in_wt_count",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "annexed_files_in_wt_size", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("head", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("head_describe", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "head_dt",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("branches", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("tags", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("git_objects_kb", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "last_update_dt",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_chk_dt",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "chk_req_dt",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("n_failed_chks", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("processed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "cache_path", sa.VARCHAR(length=34), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="url_pkey"),
        sa.UniqueConstraint("url", name="url_url_key"),
    )
    op.drop_table("repo_url")
    # ### end Alembic commands ###
